[server]
#headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[theme]
#primaryColor = "#F39C12"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#F0F2F5"
#textColor = "#000000"
#font = "sans serif"

[logger]
level = "info"